services:
  web-api:
    build:
      args:
        - ENVIRONMENT=Development
    volumes:
      - ./src:/app/src
  publisher:
    build:
      args:
        - ENVIRONMENT=Development
    volumes:
      - ./src:/app/src
  