name: fireguard

services:
  web-api:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM_NAME=fireguard
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      # kan legge til her tror jeg
      #- MONGO_DB_CONNECTION_STRING=mongodb://username:password@fireguard-database:27017/admin?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
    ports:
      - 8080:80
      - 8081:443
    
  fireguard.database:
    container_name: "fireguard-database"
    image: mongodb/mongodb-community-server:4.4.9-ubuntu2004
    restart: always
    ports:
      - 27017:27017

  keycloak:
    container_name: keycloak
    build: 
      context: .
      dockerfile: Dockerfile.keycloak
      args:
        - ADMIN=username
        - PASSWORD=password
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8090:8080"

volumes:
  keycloak_data:

