name: fireguard

services:
  web-api:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 8080:80
      - 8081:443

  keycloak:
    container_name: keycloak
    build: 
      context: .
      dockerfile: Dockerfile.keycloak
    ports:
      - 8090:8090