name: fireguard
services:
  web-api:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM_NAME=fireguard
      - MONGO_DB_CONNECTION_STRING=${MONGO_DB_CONNECTION_STRING}
      - FROST_CLIENT_ID=${FROST_CLIENT_ID}
      - FROST_CLIENT_SECRET=${FROST_CLIENT_SECRET}
    ports:
      - 8080:80
      - 8081:443
    
  fireguard.database:
    container_name: "fireguard-database"
    image: mongodb/mongodb-community-server:4.4.9-ubuntu2004
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_database:/data/db:rw

  keycloak:
    container_name: keycloak
    build: 
      context: .
      dockerfile: Dockerfile.keycloak
      args:
        - ADMIN=${KEYCLOAK_ADMIN}
        - PASSWORD=${KEYCLOAK_PASSWORD}
    #volumes:
      #- keycloak_data:/opt/keycloak/data
      #- ./src/api/authentication/keycloak/keycloak_info.json:/opt/keycloak/data/import/keycloak_info.json
    ports:
      - "8090:8080"

volumes:
  keycloak_data:
  mongodb_database:
