FROM quay.io/keycloak/keycloak
EXPOSE 8080
ARG ADMIN
ARG PASSWORD
ENV KEYCLOAK_ADMIN=${ADMIN}
ENV KEYCLOAK_ADMIN_PASSWORD=${PASSWORD}

COPY src/api/authentication/keycloak/keycloak_info.json /opt/keycloak/data/import/keycloak_info.json

CMD ["start-dev", "--import-realm"]
 
