[tool.poetry]
name = "fireguard"
version = "0.1.0"
description = ""
authors = ["h593286 <593286@stud.hvl.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.2"
requests = "^2.31.0"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
