### Token
POST http://localhost:8090/realms/fireguard/protocol/openid-connect/token
Content-Type: 'application/x-www-form-urlencoded'
 
client_id=fireguard_client
&username=admin
&password=password
&grant_type=password

### Stavanger
GET http://127.0.0.1:8080/fire_risk/5.7314/58.9700 HTTP/1.1


### Bergen
POST http://127.0.0.1:8080/fire_risk HTTP/1.1
Content-Type: 'application/json'

{
    "location": {
        "longitude": 5.3300,
        "latitude": 60.3894
    }
}