# @name GetToken
POST http://localhost:8090/realms/fireguard/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
 
client_id=fireguard_client
&username=admin
&password=password
&grant_type=password

###
@access_token = {{GetToken.response.body.access_token}}

### Bergen
GET http://localhost:8080/fire_risk/city/Bergen?ts_from=2024-05-20T21:59:59Z&ts_to=2024-08-22T18:59:59Z 
Authorization: Bearer {{access_token}}

### Get bergen info
GET http://localhost:8080/cities/Bergen
Authorization: Bearer {{access_token}}