name: Python project test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  runTests:
    name: Run Tests for projects
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install poetry
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user pipx
        pipx install poetry

    - name: Install project dependencies
      run: |
        poetry install
    - name: Run tests
      env:
        FROST_CLIENT_ID: ${{ secrets.FROST_CLIENT_ID }}
        FROST_CLIENT_SECRET: ${{ secrets.FROST_CLIENT_SECRET }}
      run:
        poetry run python3 -m unittest
        
